import './globals.css'
import SplashScreen from '@/components/SplashScreen'
import BottomNavigatoin from '@/components/BottomNavigation'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='w-screen h-screen grid grid-rows-[1fr_max-content]'>
          {/* main */}
          <SplashScreen>
            {children}
          </SplashScreen>

          <BottomNavigatoin />
        </div>
      </body>
    </html>
  )
}
